### ISSUE TITLE
screen brightness less then windows on x230t - tablet

### ISSUE THREAD

**Issue by sergvax** [banhbaoxamlan/X230-Hackintosh#25]
screen brightness less then windows on x230t - tablet

in system preference screen brightness is set to max, but it still lower then when windows runs

**Comment by medkintos** [comment]
> screen brightness less then windows on x230t - tablet
> 
> 
> 
> in system preference screen brightness is set to max, but it still lower then when windows runs

try to turn off your screen (by locking the screen) and then turn it back on. The screen will brighther

I think there's a EDID loading problem, maybe by getting EDID from Linux/Windows and apply it with Hackintool fixes the problem.

**Comment by mrfiskare** [comment]
> > screen brightness less then windows on x230t - tablet
> > in system preference screen brightness is set to max, but it still lower then when windows runs
> 
> try to turn off your screen (by locking the screen) and then turn it back on. The screen will brighther
> 
> I think there's a EDID loading problem, maybe by getting EDID from Linux/Windows and apply it with Hackintool fixes the problem.

I injected the proper EDID and the issue still exists.

**Comment by mrfiskare** [comment]
Possible solution: [AppleBacklightSmoother.kext](https://github.com/hieplpvip/AppleBacklightSmoother)

I tried this kext, and I was able to reach the maximum brightness. However, it has a problem with the slider values. With this kext, the display reaches top brightness at the middle of the slider. When the brightness slider gets past halfway it basically doesn't do anything, since it's already at top brightness. 

![brightness](https://user-images.githubusercontent.com/33120356/116392508-d0c62b00-a820-11eb-84a6-7076c646b842.png)
