### ISSUE TITLE
Support for Monterey

### ISSUE THREAD

**Issue by karelo911** [banhbaoxamlan/X230-Hackintosh#75]
It has been more than a month since MacOS Monterey came out. Is there a chance that we can get the x230 to work with Monterey?

**Comment by prabhakaran1021** [comment]
Our EFI now supports Monterey. Since im new to this repo. it is taking me a little time to test everything out.Check out the screenshot of my thinkpad x230 running Monterey 12.0.1. Also updating to 12.3.1
![Screenshot 2022-04-02 at 11 04 35 AM](https://user-images.githubusercontent.com/6811903/161368158-914ef9c2-0d11-455d-a94c-d7e92f23100d.png)
